// Generated by scripts/fonts.mjs (bun run fonts). Do not edit.
/** First-paint font files, preloaded by the layout so they load alongside the stylesheet. */
export const FONT_PRELOADS = [
	"/fonts/archivo-text.08597be6.woff2",
	"/fonts/archivo-display.19df918f.woff2",
	"/fonts/archivo-caption.becc2373.woff2",
	"/fonts/jetbrains-mono.b5d6e25a.woff2"
] as const;
